version: "3"

services:
  bind:
    image: maschel/bind:latest
    restart: unless-stopped
    container_name: bind
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    domainname: example.com
    hostname: ns1
    volumes:
      - /srv/docker/bind:/data/bind
