version: "3"

services:
  bind:
    image: maschel/bind:9.10.3-20170812
    restart: unless-stopped
    container_name: bind
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    volumes:
    - /srv/docker/bind:/data/bind
